name: 'Execução Manual'

on:
    workflow_dispatch: 

jobs:
    e2e-tests:
        runs-on: ['ubuntu-latest']

        steps:
            
            - uses: actions/checkout@v4    
        
            - name: Instalando Node
              run: sudo apt install nodejs

            - name: Instalando Cypress
              run: npm install -D cypress

            - name: Tests E2E (end-to-end)
              run: npx cypress run 